question_data = [
    {"text":"The median age of Kosovians is 30.", "answer":"true"},
    {"text":"Kosovo gained independence from Serbia in 1965.", "answer":"false"},
    {"text":"European brown bears live up to 20-30 years in the wild.", "answer":"true"},
    {"text":"Shakira's parents are from Pristina, Kosovo.", "answer":"false"},
    {"text":"40% of Kosovo is covered in forest", "answer":"true"},
    {"text":"Prizren's climate is highland temperate.", "answer":"false"},
    {"text":"The Prizren fortress was built in the 6th century.", "answer":"true"},
    {"text":"The Albanian flag includes the colour green.", "answer":"false"},
    {"text":"Lampone is Raspberry in Italian.", "answer":"true"},
    {"text":"The Mediterranean sea is not adjacent to Sicily.", "answer":"false"},
    {"text":"Malta is the 10th smallest country.", "answer":"true"},
    {"text":"Brooklyn-99 filmed in Malta.", "answer":"false"},
    {"text":"English is an official language of Malta.", "answer":"true"},
    {"text":"Calypso was thought to have lived on Gozo Island in Malta.", "answer":"true"},
    {"text":"The Beach Boys have performed in an Isle of MTV music festival.", "answer":"false"},
    {"text":"The Colosseum is the biggest amphitheatre in the world.", "answer":"true"},
    {"text":"There are around 200 drinking fountains in Rome.", "answer":"false"},
    {"text":"The Vatican City has a soccer team.", "answer":"true"},
    {"text":"Italy produces around 40 percent of the world's wine.", "answer":"false"},
    {"text":"Lake Garda is the largest lake in Italy", "answer":"true"},
    {"text":"Around 60% of italians speak English", "answer":"false"},
    {"text":"The largest diameter an authentic Neapolitan pizza can have is 13.75 inches.", "answer":"true"},
    {"text":"Norway has the 5th largest coastline in the world.", "answer":"false"},
    {"text":"Norway shares a land border with Russia", "answer":"true"},
    {"text":"Fjell means Ocean in Norwegian.", "answer":"false"},
    {"text":"Norway has knighted a penguin.", "answer":"true"},
    {"text":"The city of Stockholm is built on 2 islands.", "answer":"false"},
    {"text":"The water in Stockholm is not very salty.", "answer":"true"},
]